### PR TITLE
PR to introduce a safemode, using strategies 3 and 4 of npefix

### LINKED ISSUE #10: safe mode for npefix
with

* s3 skip statement
* S4a return null
* S4b return new (exp return constant)
* S4c return existing
* S4d return void

### PR DESCRIPTION
**Pull request by btellstrom**
This PR seeks to resolve #10

### CODE REVIEW

**Comment by tdurieux** [comment]
I think a really safe strategy should be based on the `MonoExplorerSelector` instead of ton the Greedy selector

**Comment by btellstrom** [comment]
A question, is it currently always using the "ExplorerSelector" or can some other selector be sepcified in some configuration somewhere?

**Comment by tdurieux** [comment]
I did not implement a configuration that allows for changing the configuration.
I was creating a new Main for each selector.

**Comment by monperrus** [comment]
#16 is the alternative

**Pull request closed without merging**
